name: Prod Deployment

on:
    workflow_dispatch:

env:
    DOCKER_IMAGE: ghcr.io/${{ github.repository }}:prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Build Docker image
              run: |
                  docker build -t ${{ env.DOCKER_IMAGE }} .

            - name: Push Docker image
              run: |
                  docker push ${{ env.DOCKER_IMAGE }}
